export const GET_PERSONS_SUCCESS = 'GET_PERSONS_SUCCESS';
export const GET_PERSONS_ERROR = 'GET_PERSONS_ERROR';
export const POST_PERSON_SUCCESS = 'POST_PERSON_SUCCESS';
export const POST_PERSON_ERROR = 'POST_PERSON_ERROR';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_ERROR = 'DELETE_PERSON_ERROR';